### ISSUE TITLE
Cursive broken since upgrading to 1.6.0-2017.2

### ISSUE THREAD

**Issue by AdamBoxall** [cursive-ide/cursive#1822]
I was prompted to update to the latest version of Cursive (1.6.0-2017.2) this morning, however after installation completed and IntelliJ restarted, I was presented with a dialog popup containing the following stack trace:

```
Plugin 'com.cursiveclojure.cursive' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: Could not initialize class clojure.lang.RT
    at cursive.config.InitComponent.initClojure(InitComponent.java:80)
    at cursive.config.InitComponent.initComponent(InitComponent.java:60)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:475)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:482)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:434)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:420)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:345)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

When I clicked 'OK', IntelliJ restarted again but with Cursive disabled. If I try to enable it, after restarting I see the same error, and then it's disabled automatically.

I can't find a way to _downgrade_ to the previous version. Do you have any advice on what I should do?

About IntelliJ (community edition):
```
Build #IC-172.3317.76
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by Jetbrains s.r.o
```

I'm running it on OS X 10.11.6.

**Comment by AdamBoxall** [comment]
Okay, turning it off and on again (the computer) fixed the problem, in case this helps anyone. I guess there was some dodgy temp state after trying to install.

**Comment by cursive-ide** [comment]
No, this is actually a thing, it's tracked in #1818. It's fixed in the latest EAP, and I'll get a stable build out containing it shortly. It's effectively non-deterministic since it depends on the component initialisation order in IntelliJ, which can depend on the plugins you have installed, the order in which they start up etc etc.
