### ISSUE TITLE
Cursive 1.4.0 stop working with idea 2016.3

### ISSUE THREAD

**Issue by kronos** [cursive-ide/cursive#1602]
I got this during Idea start.
```
Plugin 'com.cursiveclojure.cursive' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: Could not initialize class clojure.lang.RT
    at cursive.config.InitComponent.initClojure(InitComponent.java:100)
    at cursive.config.InitComponent.initComponent(InitComponent.java:78)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$8(ApplicationImpl.java:441)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:448)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:400)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:386)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:47)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Everything works fine and this suddenly happened after idea restarting. Any idea how to fix it?

**Comment by source-c** [comment]
Have exactly the same issue. Any progress?

**Comment by cursive-ide** [comment]
Does downloading the plugin manually from [here](https://plugins.jetbrains.com/plugin/download?pr=&updateId=30818) and then installing it using *Settings->Plugins->Install from Disk* help?

**Comment by source-c** [comment]
Thanks a lot, but `1.4.1` behaves same:
```
Plugin 'com.cursiveclojure.cursive' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: Could not initialize class clojure.lang.RT
    at cursive.config.InitComponent.initClojure(InitComponent.java:100)
    at cursive.config.InitComponent.initComponent(InitComponent.java:78)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
 ...
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by andreidemus** [comment]
it starts working after scala plugin installation :)

**Comment by source-c** [comment]
doesn't help :(

**Comment by cursive-ide** [comment]
I'm sorry I haven't been able to look into this issue, I'm travelling at the moment. I'll be stable soon and I'll look at this right away.

**Comment by cursive-ide** [comment]
Which operating systems are you all using?

**Comment by cursive-ide** [comment]
I'd also be interested to see the structure of your plugin directory. On my OSX box I can see this as follows:
```
~> tree Library/Application\ Support/IntelliJIdea2016.3/clojure-plugin/
Library/Application\ Support/IntelliJIdea2016.3/clojure-plugin/
└── lib
    ├── artem-0.5.jar
    ├── clj-stacktrace-0.2.8.jar
    ├── clj-time-0.12.2.jar
    ├── clojure-1.7.0.jar
    ├── core.rrb-vector-0.0.11.jar
    ├── cursive-1.4.1-2016.3.jar
    ├── cursive-lein-bootstrap-1.4.1-2016.3.jar
    ├── cursive-lein-shim-1.4.1-2016.3.jar
    ├── fipp-0.6.3.jar
    ├── joda-time-2.9.4.jar
    ├── jps-plugin.jar
    ├── jsr166y-1.7.0.jar
    ├── kotlin-runtime-1.0.5-2.jar
    ├── kotlin-stdlib-1.0.5-2.jar
    ├── rhino-1.7.7.jar
    ├── runtime-1.4.0-eap1-2016.2.jar
    ├── shimdandy-api-1.2.0.jar
    ├── shimdandy-impl-1.2.0.jar
    └── tools.nrepl-0.2.12.jar

1 directory, 19 files
```
For other platforms, you can see where the plugins are stored [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs). Something like a screenshot of the directory layout in Explorer would be fine (I have no idea if anything like `tree` exists on Windows).

**Comment by source-c** [comment]
```
~/.IdeaIC2016.3/config/plugins/clojure-plugin $ tree
.
└── lib
    ├── artem-0.5.jar
    ├── clj-stacktrace-0.2.8.jar
    ├── clj-time-0.12.2.jar
    ├── clojure-1.7.0.jar
    ├── core.rrb-vector-0.0.11.jar
    ├── cursive-1.4.1-2016.3.jar
    ├── cursive-lein-bootstrap-1.4.1-2016.3.jar
    ├── cursive-lein-shim-1.4.1-2016.3.jar
    ├── fipp-0.6.3.jar
    ├── joda-time-2.9.4.jar
    ├── jps-plugin.jar
    ├── jsr166y-1.7.0.jar
    ├── kotlin-runtime-1.0.5-2.jar
    ├── kotlin-stdlib-1.0.5-2.jar
    ├── rhino-1.7.7.jar
    ├── runtime-1.4.0-eap1-2016.2.jar
    ├── shimdandy-api-1.2.0.jar
    ├── shimdandy-impl-1.2.0.jar
    └── tools.nrepl-0.2.12.jar

```

**Comment by achikin** [comment]
Fails for me either.
```
IntelliJ IDEA 2016.3.1
Build #IC-163.9166.29, built on December 9, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
```
macOS Sierra
Version 10.12.1
```
```
Cursive 
Version: 1.4.2-2016.3
```

**Comment by cursive-ide** [comment]
I believe I have this issue resolved, thanks to great help from @andreidemus. There is a dev build [here](https://plugins.jetbrains.com/plugin/download?pr=idea&updateId=31398). You can install it using *Settings->Plugins->Install from disk...*. If someone suffering from this issue could confirm this build fixes the issue, it would be greatly appreciated.

**Comment by source-c** [comment]
Yeah! Great job!
It now works like a charm!
Thanks a lot!!!
